// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: file/v1/ocr.proto

package filev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PerformOCRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	PageLimit     int32                  `protobuf:"varint,3,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformOCRRequest) Reset() {
	*x = PerformOCRRequest{}
	mi := &file_file_v1_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformOCRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformOCRRequest) ProtoMessage() {}

func (x *PerformOCRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformOCRRequest.ProtoReflect.Descriptor instead.
func (*PerformOCRRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *PerformOCRRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PerformOCRRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *PerformOCRRequest) GetPageLimit() int32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

type PerformOCRResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	PagesProcessed int32                  `protobuf:"varint,2,opt,name=pages_processed,json=pagesProcessed,proto3" json:"pages_processed,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PerformOCRResponse) Reset() {
	*x = PerformOCRResponse{}
	mi := &file_file_v1_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformOCRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformOCRResponse) ProtoMessage() {}

func (x *PerformOCRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformOCRResponse.ProtoReflect.Descriptor instead.
func (*PerformOCRResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *PerformOCRResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PerformOCRResponse) GetPagesProcessed() int32 {
	if x != nil {
		return x.PagesProcessed
	}
	return 0
}

func (x *PerformOCRResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type OcrResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrResult) Reset() {
	*x = OcrResult{}
	mi := &file_file_v1_ocr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrResult) ProtoMessage() {}

func (x *OcrResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_ocr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrResult.ProtoReflect.Descriptor instead.
func (*OcrResult) Descriptor() ([]byte, []int) {
	return file_file_v1_ocr_proto_rawDescGZIP(), []int{2}
}

func (x *OcrResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OcrResult) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *OcrResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_file_v1_ocr_proto protoreflect.FileDescriptor

const file_file_v1_ocr_proto_rawDesc = "" +
	"\n" +
	"\x11file/v1/ocr.proto\x12\afile.v1\"_\n" +
	"\x11PerformOCRRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x03 \x01(\x05R\tpageLimit\"\xd5\x01\n" +
	"\x12PerformOCRResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12'\n" +
	"\x0fpages_processed\x18\x02 \x01(\x05R\x0epagesProcessed\x12E\n" +
	"\bmetadata\x18\x03 \x03(\v2).file.v1.PerformOCRResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\tOcrResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath2S\n" +
	"\n" +
	"OCRService\x12E\n" +
	"\n" +
	"PerformOCR\x12\x1a.file.v1.PerformOCRRequest\x1a\x1b.file.v1.PerformOCRResponseB3Z1github.com/bexprt/bexgen-client/pb/file/v1;filev1b\x06proto3"

var (
	file_file_v1_ocr_proto_rawDescOnce sync.Once
	file_file_v1_ocr_proto_rawDescData []byte
)

func file_file_v1_ocr_proto_rawDescGZIP() []byte {
	file_file_v1_ocr_proto_rawDescOnce.Do(func() {
		file_file_v1_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_v1_ocr_proto_rawDesc), len(file_file_v1_ocr_proto_rawDesc)))
	})
	return file_file_v1_ocr_proto_rawDescData
}

var file_file_v1_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_v1_ocr_proto_goTypes = []any{
	(*PerformOCRRequest)(nil),  // 0: file.v1.PerformOCRRequest
	(*PerformOCRResponse)(nil), // 1: file.v1.PerformOCRResponse
	(*OcrResult)(nil),          // 2: file.v1.OcrResult
	nil,                        // 3: file.v1.PerformOCRResponse.MetadataEntry
}
var file_file_v1_ocr_proto_depIdxs = []int32{
	3, // 0: file.v1.PerformOCRResponse.metadata:type_name -> file.v1.PerformOCRResponse.MetadataEntry
	0, // 1: file.v1.OCRService.PerformOCR:input_type -> file.v1.PerformOCRRequest
	1, // 2: file.v1.OCRService.PerformOCR:output_type -> file.v1.PerformOCRResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_file_v1_ocr_proto_init() }
func file_file_v1_ocr_proto_init() {
	if File_file_v1_ocr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_v1_ocr_proto_rawDesc), len(file_file_v1_ocr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_v1_ocr_proto_goTypes,
		DependencyIndexes: file_file_v1_ocr_proto_depIdxs,
		MessageInfos:      file_file_v1_ocr_proto_msgTypes,
	}.Build()
	File_file_v1_ocr_proto = out.File
	file_file_v1_ocr_proto_goTypes = nil
	file_file_v1_ocr_proto_depIdxs = nil
}
