// proto/file/upload.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: file/v1/upload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	UploadedAt    int64                  `protobuf:"varint,5,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUpload) Reset() {
	*x = FileUpload{}
	mi := &file_file_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpload) ProtoMessage() {}

func (x *FileUpload) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpload.ProtoReflect.Descriptor instead.
func (*FileUpload) Descriptor() ([]byte, []int) {
	return file_file_v1_upload_proto_rawDescGZIP(), []int{0}
}

func (x *FileUpload) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileUpload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUpload) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileUpload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileUpload) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

var File_file_v1_upload_proto protoreflect.FileDescriptor

const file_file_v1_upload_proto_rawDesc = "" +
	"\n" +
	"\x14file/v1/upload.proto\x12\afile.v1\"\xa4\x01\n" +
	"\n" +
	"FileUpload\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vuploaded_at\x18\x05 \x01(\x03R\n" +
	"uploadedAtB'Z%github.com/bexprt/bexgen-client/pb;pbb\x06proto3"

var (
	file_file_v1_upload_proto_rawDescOnce sync.Once
	file_file_v1_upload_proto_rawDescData []byte
)

func file_file_v1_upload_proto_rawDescGZIP() []byte {
	file_file_v1_upload_proto_rawDescOnce.Do(func() {
		file_file_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_v1_upload_proto_rawDesc), len(file_file_v1_upload_proto_rawDesc)))
	})
	return file_file_v1_upload_proto_rawDescData
}

var file_file_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_file_v1_upload_proto_goTypes = []any{
	(*FileUpload)(nil), // 0: file.v1.FileUpload
}
var file_file_v1_upload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_v1_upload_proto_init() }
func file_file_v1_upload_proto_init() {
	if File_file_v1_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_v1_upload_proto_rawDesc), len(file_file_v1_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_v1_upload_proto_goTypes,
		DependencyIndexes: file_file_v1_upload_proto_depIdxs,
		MessageInfos:      file_file_v1_upload_proto_msgTypes,
	}.Build()
	File_file_v1_upload_proto = out.File
	file_file_v1_upload_proto_goTypes = nil
	file_file_v1_upload_proto_depIdxs = nil
}
