//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProcessingStepState.
const (
	ProcessingStepStateCompleted  ProcessingStepState = "completed"
	ProcessingStepStateFailed     ProcessingStepState = "failed"
	ProcessingStepStatePending    ProcessingStepState = "pending"
	ProcessingStepStateProcessing ProcessingStepState = "processing"
)

// Defines values for ListDocumentStatusesParamsState.
const (
	ListDocumentStatusesParamsStateCompleted  ListDocumentStatusesParamsState = "completed"
	ListDocumentStatusesParamsStateFailed     ListDocumentStatusesParamsState = "failed"
	ListDocumentStatusesParamsStatePending    ListDocumentStatusesParamsState = "pending"
	ListDocumentStatusesParamsStateProcessing ListDocumentStatusesParamsState = "processing"
)

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action    *string                 `json:"action,omitempty"`
	Actor     *string                 `json:"actor,omitempty"`
	EventId   *openapi_types.UUID     `json:"event_id,omitempty"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	Resource  *string                 `json:"resource,omitempty"`
	Timestamp *time.Time              `json:"timestamp,omitempty"`
}

// AuditResponse defines model for AuditResponse.
type AuditResponse struct {
	DocumentId *openapi_types.UUID `json:"document_id,omitempty"`
	Events     *[]AuditEvent       `json:"events,omitempty"`
}

// Document defines model for Document.
type Document struct {
	ContentType *string              `json:"content_type,omitempty"`
	CreatedAt   *time.Time           `json:"created_at,omitempty"`
	Filename    *string              `json:"filename,omitempty"`
	Id          *openapi_types.UUID  `json:"id,omitempty"`
	SizeBytes   *int                 `json:"size_bytes,omitempty"`
	Summary     *string              `json:"summary,omitempty"`
	UpdatedAt   *time.Time           `json:"updated_at,omitempty"`
	UserEmail   *openapi_types.Email `json:"user_email,omitempty"`
}

// DocumentStatus defines model for DocumentStatus.
type DocumentStatus struct {
	DocumentId *openapi_types.UUID `json:"document_id,omitempty"`
	Steps      *[]ProcessingStep   `json:"steps,omitempty"`
}

// DocumentUploadResponse defines model for DocumentUploadResponse.
type DocumentUploadResponse struct {
	CreatedAt *time.Time           `json:"created_at,omitempty"`
	Id        *openapi_types.UUID  `json:"id,omitempty"`
	Status    *string              `json:"status,omitempty"`
	UserEmail *openapi_types.Email `json:"user_email,omitempty"`
}

// ProcessingStep defines model for ProcessingStep.
type ProcessingStep struct {
	Message   *string              `json:"message,omitempty"`
	State     *ProcessingStepState `json:"state,omitempty"`
	StepName  *string              `json:"step_name,omitempty"`
	UpdatedAt *time.Time           `json:"updated_at,omitempty"`
}

// ProcessingStepState defines model for ProcessingStep.State.
type ProcessingStepState string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Results *[]SearchResult `json:"results,omitempty"`
	Total   *int            `json:"total,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Id      *openapi_types.UUID `json:"id,omitempty"`
	Score   *float32            `json:"score,omitempty"`
	Snippet *string             `json:"snippet,omitempty"`
	Summary *string             `json:"summary,omitempty"`
}

// VectorSearchRequest defines model for VectorSearchRequest.
type VectorSearchRequest struct {
	Text      *string              `json:"text,omitempty"`
	TopK      *int                 `json:"top_k,omitempty"`
	UserEmail *openapi_types.Email `json:"user_email,omitempty"`
}

// DocumentId defines model for DocumentId.
type DocumentId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// UploadDocumentMultipartBody defines parameters for UploadDocument.
type UploadDocumentMultipartBody struct {
	File      openapi_types.File  `json:"file"`
	UserEmail openapi_types.Email `json:"user_email"`
}

// ListDocumentAuditParams defines parameters for ListDocumentAudit.
type ListDocumentAuditParams struct {
	DocumentId *openapi_types.UUID `form:"document_id,omitempty" json:"document_id,omitempty"`
	Action     *string             `form:"action,omitempty" json:"action,omitempty"`
	Actor      *string             `form:"actor,omitempty" json:"actor,omitempty"`
	From       *time.Time          `form:"from,omitempty" json:"from,omitempty"`
	To         *time.Time          `form:"to,omitempty" json:"to,omitempty"`
	Limit      *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset             `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchDocumentsParams defines parameters for SearchDocuments.
type SearchDocumentsParams struct {
	Query     string               `form:"query" json:"query"`
	UserEmail *openapi_types.Email `form:"user_email,omitempty" json:"user_email,omitempty"`
	Limit     *Limit               `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *Offset              `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListDocumentStatusesParams defines parameters for ListDocumentStatuses.
type ListDocumentStatusesParams struct {
	UserEmail *openapi_types.Email             `form:"user_email,omitempty" json:"user_email,omitempty"`
	State     *ListDocumentStatusesParamsState `form:"state,omitempty" json:"state,omitempty"`
	Limit     *Limit                           `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *Offset                          `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListDocumentStatusesParamsState defines parameters for ListDocumentStatuses.
type ListDocumentStatusesParamsState string

// UploadDocumentMultipartRequestBody defines body for UploadDocument for multipart/form-data ContentType.
type UploadDocumentMultipartRequestBody UploadDocumentMultipartBody

// VectorSearchDocumentsJSONRequestBody defines body for VectorSearchDocuments for application/json ContentType.
type VectorSearchDocumentsJSONRequestBody = VectorSearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload a document
	// (POST /documents)
	UploadDocument(w http.ResponseWriter, r *http.Request)
	// Get audit logs across documents
	// (GET /documents/audit)
	ListDocumentAudit(w http.ResponseWriter, r *http.Request, params ListDocumentAuditParams)
	// Search documents (text search)
	// (GET /documents/search)
	SearchDocuments(w http.ResponseWriter, r *http.Request, params SearchDocumentsParams)
	// Get processing status for documents
	// (GET /documents/status)
	ListDocumentStatuses(w http.ResponseWriter, r *http.Request, params ListDocumentStatusesParams)
	// Vector similarity search
	// (POST /documents/vector-search)
	VectorSearchDocuments(w http.ResponseWriter, r *http.Request)
	// Get document by ID
	// (GET /documents/{id})
	GetDocumentById(w http.ResponseWriter, r *http.Request, id DocumentId)
	// Get document audit log
	// (GET /documents/{id}/audit)
	GetDocumentAudit(w http.ResponseWriter, r *http.Request, id DocumentId)
	// Get document processing status
	// (GET /documents/{id}/status)
	GetDocumentStatus(w http.ResponseWriter, r *http.Request, id DocumentId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadDocument operation middleware
func (siw *ServerInterfaceWrapper) UploadDocument(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadDocument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDocumentAudit operation middleware
func (siw *ServerInterfaceWrapper) ListDocumentAudit(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDocumentAuditParams

	// ------------- Optional query parameter "document_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "document_id", r.URL.Query(), &params.DocumentId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "document_id", Err: err})
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameter("form", true, false, "action", r.URL.Query(), &params.Action)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	// ------------- Optional query parameter "actor" -------------

	err = runtime.BindQueryParameter("form", true, false, "actor", r.URL.Query(), &params.Actor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDocumentAudit(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchDocuments operation middleware
func (siw *ServerInterfaceWrapper) SearchDocuments(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchDocumentsParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	// ------------- Optional query parameter "user_email" -------------

	err = runtime.BindQueryParameter("form", true, false, "user_email", r.URL.Query(), &params.UserEmail)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_email", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchDocuments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDocumentStatuses operation middleware
func (siw *ServerInterfaceWrapper) ListDocumentStatuses(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDocumentStatusesParams

	// ------------- Optional query parameter "user_email" -------------

	err = runtime.BindQueryParameter("form", true, false, "user_email", r.URL.Query(), &params.UserEmail)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_email", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDocumentStatuses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VectorSearchDocuments operation middleware
func (siw *ServerInterfaceWrapper) VectorSearchDocuments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VectorSearchDocuments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocumentById operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DocumentId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocumentAudit operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentAudit(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DocumentId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentAudit(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocumentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DocumentId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/documents", wrapper.UploadDocument)
	m.HandleFunc("GET "+options.BaseURL+"/documents/audit", wrapper.ListDocumentAudit)
	m.HandleFunc("GET "+options.BaseURL+"/documents/search", wrapper.SearchDocuments)
	m.HandleFunc("GET "+options.BaseURL+"/documents/status", wrapper.ListDocumentStatuses)
	m.HandleFunc("POST "+options.BaseURL+"/documents/vector-search", wrapper.VectorSearchDocuments)
	m.HandleFunc("GET "+options.BaseURL+"/documents/{id}", wrapper.GetDocumentById)
	m.HandleFunc("GET "+options.BaseURL+"/documents/{id}/audit", wrapper.GetDocumentAudit)
	m.HandleFunc("GET "+options.BaseURL+"/documents/{id}/status", wrapper.GetDocumentStatus)

	return m
}

type UploadDocumentRequestObject struct {
	Body *multipart.Reader
}

type UploadDocumentResponseObject interface {
	VisitUploadDocumentResponse(w http.ResponseWriter) error
}

type UploadDocument201JSONResponse DocumentUploadResponse

func (response UploadDocument201JSONResponse) VisitUploadDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type ListDocumentAuditRequestObject struct {
	Params ListDocumentAuditParams
}

type ListDocumentAuditResponseObject interface {
	VisitListDocumentAuditResponse(w http.ResponseWriter) error
}

type ListDocumentAudit200JSONResponse struct {
	Results *[]AuditEvent `json:"results,omitempty"`
	Total   *int          `json:"total,omitempty"`
}

func (response ListDocumentAudit200JSONResponse) VisitListDocumentAuditResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchDocumentsRequestObject struct {
	Params SearchDocumentsParams
}

type SearchDocumentsResponseObject interface {
	VisitSearchDocumentsResponse(w http.ResponseWriter) error
}

type SearchDocuments200JSONResponse SearchResponse

func (response SearchDocuments200JSONResponse) VisitSearchDocumentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDocumentStatusesRequestObject struct {
	Params ListDocumentStatusesParams
}

type ListDocumentStatusesResponseObject interface {
	VisitListDocumentStatusesResponse(w http.ResponseWriter) error
}

type ListDocumentStatuses200JSONResponse struct {
	Results *[]DocumentStatus `json:"results,omitempty"`
	Total   *int              `json:"total,omitempty"`
}

func (response ListDocumentStatuses200JSONResponse) VisitListDocumentStatusesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VectorSearchDocumentsRequestObject struct {
	Body *VectorSearchDocumentsJSONRequestBody
}

type VectorSearchDocumentsResponseObject interface {
	VisitVectorSearchDocumentsResponse(w http.ResponseWriter) error
}

type VectorSearchDocuments200JSONResponse SearchResponse

func (response VectorSearchDocuments200JSONResponse) VisitVectorSearchDocumentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentByIdRequestObject struct {
	Id DocumentId `json:"id"`
}

type GetDocumentByIdResponseObject interface {
	VisitGetDocumentByIdResponse(w http.ResponseWriter) error
}

type GetDocumentById200JSONResponse Document

func (response GetDocumentById200JSONResponse) VisitGetDocumentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentById404Response struct {
}

func (response GetDocumentById404Response) VisitGetDocumentByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetDocumentAuditRequestObject struct {
	Id DocumentId `json:"id"`
}

type GetDocumentAuditResponseObject interface {
	VisitGetDocumentAuditResponse(w http.ResponseWriter) error
}

type GetDocumentAudit200JSONResponse AuditResponse

func (response GetDocumentAudit200JSONResponse) VisitGetDocumentAuditResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentStatusRequestObject struct {
	Id DocumentId `json:"id"`
}

type GetDocumentStatusResponseObject interface {
	VisitGetDocumentStatusResponse(w http.ResponseWriter) error
}

type GetDocumentStatus200JSONResponse DocumentStatus

func (response GetDocumentStatus200JSONResponse) VisitGetDocumentStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Upload a document
	// (POST /documents)
	UploadDocument(ctx context.Context, request UploadDocumentRequestObject) (UploadDocumentResponseObject, error)
	// Get audit logs across documents
	// (GET /documents/audit)
	ListDocumentAudit(ctx context.Context, request ListDocumentAuditRequestObject) (ListDocumentAuditResponseObject, error)
	// Search documents (text search)
	// (GET /documents/search)
	SearchDocuments(ctx context.Context, request SearchDocumentsRequestObject) (SearchDocumentsResponseObject, error)
	// Get processing status for documents
	// (GET /documents/status)
	ListDocumentStatuses(ctx context.Context, request ListDocumentStatusesRequestObject) (ListDocumentStatusesResponseObject, error)
	// Vector similarity search
	// (POST /documents/vector-search)
	VectorSearchDocuments(ctx context.Context, request VectorSearchDocumentsRequestObject) (VectorSearchDocumentsResponseObject, error)
	// Get document by ID
	// (GET /documents/{id})
	GetDocumentById(ctx context.Context, request GetDocumentByIdRequestObject) (GetDocumentByIdResponseObject, error)
	// Get document audit log
	// (GET /documents/{id}/audit)
	GetDocumentAudit(ctx context.Context, request GetDocumentAuditRequestObject) (GetDocumentAuditResponseObject, error)
	// Get document processing status
	// (GET /documents/{id}/status)
	GetDocumentStatus(ctx context.Context, request GetDocumentStatusRequestObject) (GetDocumentStatusResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// UploadDocument operation middleware
func (sh *strictHandler) UploadDocument(w http.ResponseWriter, r *http.Request) {
	var request UploadDocumentRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadDocument(ctx, request.(UploadDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadDocumentResponseObject); ok {
		if err := validResponse.VisitUploadDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDocumentAudit operation middleware
func (sh *strictHandler) ListDocumentAudit(w http.ResponseWriter, r *http.Request, params ListDocumentAuditParams) {
	var request ListDocumentAuditRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDocumentAudit(ctx, request.(ListDocumentAuditRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDocumentAudit")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDocumentAuditResponseObject); ok {
		if err := validResponse.VisitListDocumentAuditResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchDocuments operation middleware
func (sh *strictHandler) SearchDocuments(w http.ResponseWriter, r *http.Request, params SearchDocumentsParams) {
	var request SearchDocumentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchDocuments(ctx, request.(SearchDocumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchDocuments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchDocumentsResponseObject); ok {
		if err := validResponse.VisitSearchDocumentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDocumentStatuses operation middleware
func (sh *strictHandler) ListDocumentStatuses(w http.ResponseWriter, r *http.Request, params ListDocumentStatusesParams) {
	var request ListDocumentStatusesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDocumentStatuses(ctx, request.(ListDocumentStatusesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDocumentStatuses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDocumentStatusesResponseObject); ok {
		if err := validResponse.VisitListDocumentStatusesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VectorSearchDocuments operation middleware
func (sh *strictHandler) VectorSearchDocuments(w http.ResponseWriter, r *http.Request) {
	var request VectorSearchDocumentsRequestObject

	var body VectorSearchDocumentsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VectorSearchDocuments(ctx, request.(VectorSearchDocumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VectorSearchDocuments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VectorSearchDocumentsResponseObject); ok {
		if err := validResponse.VisitVectorSearchDocumentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocumentById operation middleware
func (sh *strictHandler) GetDocumentById(w http.ResponseWriter, r *http.Request, id DocumentId) {
	var request GetDocumentByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocumentById(ctx, request.(GetDocumentByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocumentById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentByIdResponseObject); ok {
		if err := validResponse.VisitGetDocumentByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocumentAudit operation middleware
func (sh *strictHandler) GetDocumentAudit(w http.ResponseWriter, r *http.Request, id DocumentId) {
	var request GetDocumentAuditRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocumentAudit(ctx, request.(GetDocumentAuditRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocumentAudit")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentAuditResponseObject); ok {
		if err := validResponse.VisitGetDocumentAuditResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocumentStatus operation middleware
func (sh *strictHandler) GetDocumentStatus(w http.ResponseWriter, r *http.Request, id DocumentId) {
	var request GetDocumentStatusRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocumentStatus(ctx, request.(GetDocumentStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocumentStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentStatusResponseObject); ok {
		if err := validResponse.VisitGetDocumentStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xY3W4bNxN9lQW/76IFNpLcpje6c+AiMBCgRoPmxjEEejkrM1n+mBwaUQ29e0Fyf7Vc",
	"eWUnhdE7SSRnh2fOnDmrR1IooZUEiZasH4mmhgpAMOHbhSqcAImXzH/jkqyJpnhHciKpALImnJGcGLh3",
	"3AAjazQOcmKLOxDUnyiVERTJmjgXduJO+1MWDZdbst/n5AMXHNvg9w7MrotehcV+QAYldRWS9dmqjcYl",
	"whZMCPdHWVqYjKfiajJgKt6+2RnAOHeM4+8PIEN8bZQGgxzCGi2QK+k/HVwx90vKJFfAx9pwNgOpnAhA",
	"yiiGpClj3D+PVle9LCL49UF1+wUK9AcNWOVMAckUkAuwSIUe5MAowhu/lCzZ6AkBmD/BaiUtjLFhNYnm",
	"3jTAEk5yBBE+/N9ASdbkf8uOrMu6MsteWbrkqDF0l8624fQ40UJJ9HnGIwm0CgMUgW0ozoUrJyWvINIv",
	"EXAmIpb/DZvbHcY0D2maE+uEoGaXfITT7OScnQWzAUF5NTgTf5lFiQbkj0jR2ZdzwiLo+ZS4MqoAa7nc",
	"fkTQp9HiL10pyqbZ/BwOzL5kAxZ8o0JXftWFdID9mDIdADW6rABr6TbNXZ9tWAHpBFlfEw2S+bXcB6nD",
	"kjzMlwowXKGkvAJGbiYqvJlslNNZnLruR6CmuJuurQHrqhOkp43nJ8iIZTlBhbRKtezR5MI4OkxtLoUK",
	"ZfoISidua42QXOs4GsenJvUjlegn8BOtSffegU3ki/At/SxUevN1MHl/yxOS9lJu+5+4LFV8ki0M13FC",
	"k/Ory6xUJoudxeU2z2y4S/hIJcsElXTL5TareQwsa/TKfpZcFpXz57KHAER9Os9i+2ZoaPG1jUX9dMoq",
	"tbWLz9InzjH0dSM3WdeC2fnVJcnJAxgbMz1brBYrD4bSIKnmZE1+XZwtVr7DKN4FnJdtZqEGKtbCV4L6",
	"+3rjRqKktXMvGjaw+E6xXW/uhYZ3FXJNDS495G8aw9H5pWGV/XAb1OeWSxoc18vFqnOV1/E5gxg3yYoP",
	"nWg0P6HXQ7a/rM4Orku1rngRkFp+sdHAdXc91voT4yJkMeRbW+lGyjPrCl/y0lVVHEZt/9WlymhLuLDe",
	"FXkZ+OST20Ki0h+4xeZ5wRcFqnSO/jrti/vT+CT7ng5Xm+F+pPknlXnOwdIokU796IhIB0P1rFApunTg",
	"L+ObzoyN9TvM/mZE39VJ9H3ZbDtmq0+abOOOOG80MQOJxuc3bIL3gD3dzGhhlLWdBB+2RNTfyZ6Ig+qi",
	"PT2rI5qv06+2M7nUk6wkpyb17/XxaZYTmpTBuCNraDiseL3Y1jT7yfuHerL+PCp465OfFMH4/gEzq/6C",
	"YqXCRYfcj/Q9rPJ/T2oOXha/t9x4PmSqbNlVG7Wk7HTlaOyct4qT0hMd4JtOgdIGrO+Y+0I07cOe34kp",
	"dz7LG/2bYvCp75wnNKHZwwWvqOG4q7cf1uCRs/2kFryHVgre7S7ZWAaeaJDeH6A/VD8vOrs3bSAZIOVV",
	"aJC3q7fjN5t2o1SYlcpJlmB42wW3u+zyIgXmEx6zB+mExXwlmA7/lnymD2nhag1JErInRlIPs1rkXjsR",
	"Gy0+QseRVh6DL7XZ7wbz0CDgTEXW5A5R2/VySTVf1H+DLQollg9nZH+z/ycAAP//FxAlkK8YAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
