// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: classification/v1/classification.proto

package classificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_classification_v1_classification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_classification_v1_classification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_classification_v1_classification_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type Subcategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subcategory) Reset() {
	*x = Subcategory{}
	mi := &file_classification_v1_classification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subcategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subcategory) ProtoMessage() {}

func (x *Subcategory) ProtoReflect() protoreflect.Message {
	mi := &file_classification_v1_classification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subcategory.ProtoReflect.Descriptor instead.
func (*Subcategory) Descriptor() ([]byte, []int) {
	return file_classification_v1_classification_proto_rawDescGZIP(), []int{1}
}

func (x *Subcategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subcategory) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Subcategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Subcategory) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	Subcategories []*Subcategory         `protobuf:"bytes,3,rep,name=subcategories,proto3" json:"subcategories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_classification_v1_classification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classification_v1_classification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_classification_v1_classification_proto_rawDescGZIP(), []int{2}
}

func (x *ClassifyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ClassifyRequest) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ClassifyRequest) GetSubcategories() []*Subcategory {
	if x != nil {
		return x.Subcategories
	}
	return nil
}

type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_classification_v1_classification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classification_v1_classification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_classification_v1_classification_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifyResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ClassifyResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClassifyResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type ClassifyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResult) Reset() {
	*x = ClassifyResult{}
	mi := &file_classification_v1_classification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResult) ProtoMessage() {}

func (x *ClassifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_classification_v1_classification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResult.ProtoReflect.Descriptor instead.
func (*ClassifyResult) Descriptor() ([]byte, []int) {
	return file_classification_v1_classification_proto_rawDescGZIP(), []int{4}
}

func (x *ClassifyResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClassifyResult) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ClassifyResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClassifyResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_classification_v1_classification_proto protoreflect.FileDescriptor

const file_classification_v1_classification_proto_rawDesc = "" +
	"\n" +
	"&classification/v1/classification.proto\x12\x11classification.v1\"^\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\"}\n" +
	"\vSubcategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tembedding\x18\x04 \x03(\x02R\tembedding\"\xa8\x01\n" +
	"\x0fClassifyRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12;\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x1b.classification.v1.CategoryR\n" +
	"categories\x12D\n" +
	"\rsubcategories\x18\x03 \x03(\v2\x1e.classification.v1.SubcategoryR\rsubcategories\"d\n" +
	"\x10ClassifyResponse\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\"r\n" +
	"\x0eClassifyResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence2p\n" +
	"\x19DocumentClassifierService\x12S\n" +
	"\bClassify\x12\".classification.v1.ClassifyRequest\x1a#.classification.v1.ClassifyResponseBGZEgithub.com/bexprt/bexgen-client/pb/classification/v1;classificationv1b\x06proto3"

var (
	file_classification_v1_classification_proto_rawDescOnce sync.Once
	file_classification_v1_classification_proto_rawDescData []byte
)

func file_classification_v1_classification_proto_rawDescGZIP() []byte {
	file_classification_v1_classification_proto_rawDescOnce.Do(func() {
		file_classification_v1_classification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classification_v1_classification_proto_rawDesc), len(file_classification_v1_classification_proto_rawDesc)))
	})
	return file_classification_v1_classification_proto_rawDescData
}

var file_classification_v1_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_classification_v1_classification_proto_goTypes = []any{
	(*Category)(nil),         // 0: classification.v1.Category
	(*Subcategory)(nil),      // 1: classification.v1.Subcategory
	(*ClassifyRequest)(nil),  // 2: classification.v1.ClassifyRequest
	(*ClassifyResponse)(nil), // 3: classification.v1.ClassifyResponse
	(*ClassifyResult)(nil),   // 4: classification.v1.ClassifyResult
}
var file_classification_v1_classification_proto_depIdxs = []int32{
	0, // 0: classification.v1.ClassifyRequest.categories:type_name -> classification.v1.Category
	1, // 1: classification.v1.ClassifyRequest.subcategories:type_name -> classification.v1.Subcategory
	2, // 2: classification.v1.DocumentClassifierService.Classify:input_type -> classification.v1.ClassifyRequest
	3, // 3: classification.v1.DocumentClassifierService.Classify:output_type -> classification.v1.ClassifyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_classification_v1_classification_proto_init() }
func file_classification_v1_classification_proto_init() {
	if File_classification_v1_classification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classification_v1_classification_proto_rawDesc), len(file_classification_v1_classification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_classification_v1_classification_proto_goTypes,
		DependencyIndexes: file_classification_v1_classification_proto_depIdxs,
		MessageInfos:      file_classification_v1_classification_proto_msgTypes,
	}.Build()
	File_classification_v1_classification_proto = out.File
	file_classification_v1_classification_proto_goTypes = nil
	file_classification_v1_classification_proto_depIdxs = nil
}
