// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: classification/v1/classification.proto

package classificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentClassifierService_Classify_FullMethodName = "/classification.v1.DocumentClassifierService/Classify"
)

// DocumentClassifierServiceClient is the client API for DocumentClassifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentClassifierServiceClient interface {
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
}

type documentClassifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentClassifierServiceClient(cc grpc.ClientConnInterface) DocumentClassifierServiceClient {
	return &documentClassifierServiceClient{cc}
}

func (c *documentClassifierServiceClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, DocumentClassifierService_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentClassifierServiceServer is the server API for DocumentClassifierService service.
// All implementations must embed UnimplementedDocumentClassifierServiceServer
// for forward compatibility.
type DocumentClassifierServiceServer interface {
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	mustEmbedUnimplementedDocumentClassifierServiceServer()
}

// UnimplementedDocumentClassifierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentClassifierServiceServer struct{}

func (UnimplementedDocumentClassifierServiceServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedDocumentClassifierServiceServer) mustEmbedUnimplementedDocumentClassifierServiceServer() {
}
func (UnimplementedDocumentClassifierServiceServer) testEmbeddedByValue() {}

// UnsafeDocumentClassifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentClassifierServiceServer will
// result in compilation errors.
type UnsafeDocumentClassifierServiceServer interface {
	mustEmbedUnimplementedDocumentClassifierServiceServer()
}

func RegisterDocumentClassifierServiceServer(s grpc.ServiceRegistrar, srv DocumentClassifierServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentClassifierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentClassifierService_ServiceDesc, srv)
}

func _DocumentClassifierService_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentClassifierServiceServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentClassifierService_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentClassifierServiceServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentClassifierService_ServiceDesc is the grpc.ServiceDesc for DocumentClassifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentClassifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classification.v1.DocumentClassifierService",
	HandlerType: (*DocumentClassifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _DocumentClassifierService_Classify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classification/v1/classification.proto",
}
