// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessingState string

const (
	ProcessingStateProcessing ProcessingState = "processing"
	ProcessingStateComplete   ProcessingState = "complete"
	ProcessingStateFailed     ProcessingState = "failed"
)

func (e *ProcessingState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingState(s)
	case string:
		*e = ProcessingState(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingState: %T", src)
	}
	return nil
}

type NullProcessingState struct {
	ProcessingState ProcessingState `json:"processing_state"`
	Valid           bool            `json:"valid"` // Valid is true if ProcessingState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingState) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingState), nil
}

type RetryState string

const (
	RetryStatePending    RetryState = "pending"
	RetryStateRetried    RetryState = "retried"
	RetryStateDeadLetter RetryState = "dead_letter"
)

func (e *RetryState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RetryState(s)
	case string:
		*e = RetryState(s)
	default:
		return fmt.Errorf("unsupported scan type for RetryState: %T", src)
	}
	return nil
}

type NullRetryState struct {
	RetryState RetryState `json:"retry_state"`
	Valid      bool       `json:"valid"` // Valid is true if RetryState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRetryState) Scan(value interface{}) error {
	if value == nil {
		ns.RetryState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RetryState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRetryState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RetryState), nil
}

type Document struct {
	ID             pgtype.UUID        `json:"id"`
	Filename       pgtype.Text        `json:"filename"`
	Filepath       pgtype.Text        `json:"filepath"`
	Classification pgtype.Text        `json:"classification"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DocumentStatus struct {
	DocumentID pgtype.UUID        `json:"document_id"`
	StepName   string             `json:"step_name"`
	State      ProcessingState    `json:"state"`
	Message    pgtype.Text        `json:"message"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type FailedMessage struct {
	ID              pgtype.UUID        `json:"id"`
	DocumentID      pgtype.UUID        `json:"document_id"`
	TopicName       string             `json:"topic_name"`
	ProtobufPayload []byte             `json:"protobuf_payload"`
	Headers         []byte             `json:"headers"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	RetryCount      pgtype.Int4        `json:"retry_count"`
	RetryState      NullRetryState     `json:"retry_state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastRetryAt     pgtype.Timestamptz `json:"last_retry_at"`
}

type ProcessingStep struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
