// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ProcessingState string

const (
	ProcessingStateProcessing ProcessingState = "processing"
	ProcessingStateComplete   ProcessingState = "complete"
	ProcessingStateFailed     ProcessingState = "failed"
)

func (e *ProcessingState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingState(s)
	case string:
		*e = ProcessingState(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingState: %T", src)
	}
	return nil
}

type NullProcessingState struct {
	ProcessingState ProcessingState `json:"processing_state"`
	Valid           bool            `json:"valid"` // Valid is true if ProcessingState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingState) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingState), nil
}

type RetryState string

const (
	RetryStatePending    RetryState = "pending"
	RetryStateRetried    RetryState = "retried"
	RetryStateDeadLetter RetryState = "dead_letter"
)

func (e *RetryState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RetryState(s)
	case string:
		*e = RetryState(s)
	default:
		return fmt.Errorf("unsupported scan type for RetryState: %T", src)
	}
	return nil
}

type NullRetryState struct {
	RetryState RetryState `json:"retry_state"`
	Valid      bool       `json:"valid"` // Valid is true if RetryState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRetryState) Scan(value interface{}) error {
	if value == nil {
		ns.RetryState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RetryState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRetryState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RetryState), nil
}

type AuditEvent struct {
	ID         uuid.UUID          `json:"id"`
	ResourceID pgtype.UUID        `json:"resource_id"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	Actor      pgtype.Text        `json:"actor"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Embedding   []float32        `json:"embedding"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Document struct {
	ID             uuid.UUID          `json:"id"`
	Filename       pgtype.Text        `json:"filename"`
	Filepath       pgtype.Text        `json:"filepath"`
	Classification pgtype.Text        `json:"classification"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DocumentStatus struct {
	DocumentID uuid.UUID          `json:"document_id"`
	StepName   string             `json:"step_name"`
	State      string             `json:"state"`
	Message    pgtype.Text        `json:"message"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type FailedMessage struct {
	ID              uuid.UUID          `json:"id"`
	DocumentID      pgtype.UUID        `json:"document_id"`
	TopicName       string             `json:"topic_name"`
	ProtobufPayload []byte             `json:"protobuf_payload"`
	Headers         []byte             `json:"headers"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	RetryCount      pgtype.Int4        `json:"retry_count"`
	RetryState      NullRetryState     `json:"retry_state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastRetryAt     pgtype.Timestamptz `json:"last_retry_at"`
}

type Metadata struct {
	ID                 int32              `json:"id"`
	SiteID             pgtype.Text        `json:"site_id"`
	DocumentType       pgtype.Text        `json:"document_type"`
	Confidence         pgtype.Float8      `json:"confidence"`
	DocumentDate       pgtype.Date        `json:"document_date"`
	PortfolioType      pgtype.Text        `json:"portfolio_type"`
	DocumentAmount     pgtype.Float8      `json:"document_amount"`
	LicensedEntity     pgtype.Text        `json:"licensed_entity"`
	LicensingAuthority pgtype.Text        `json:"licensing_authority"`
	DocumentFolder     pgtype.Text        `json:"document_folder"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ProcessingStep struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Site struct {
	ID                       int32              `json:"id"`
	Pk                       pgtype.Text        `json:"pk"`
	EmbeddingLandlord        pgvector.Vector    `json:"embedding_landlord"`
	EmbeddingSiteAddress     pgvector.Vector    `json:"embedding_site_address"`
	EmbeddingLandlordAddress pgvector.Vector    `json:"embedding_landlord_address"`
	Timestamp                pgtype.Timestamptz `json:"timestamp"`
	SiteCode                 pgtype.Text        `json:"site_code"`
	PortfolioType            pgtype.Text        `json:"portfolio_type"`
	Channel                  pgtype.Text        `json:"channel"`
	UseType                  pgtype.Text        `json:"use_type"`
	Name                     pgtype.Text        `json:"name"`
	Status                   pgtype.Text        `json:"status"`
	SprintCascadeID          pgtype.Text        `json:"sprint_cascade_id"`
	Address                  pgtype.Text        `json:"address"`
	Address2                 pgtype.Text        `json:"address2"`
	City                     pgtype.Text        `json:"city"`
	State                    pgtype.Text        `json:"state"`
	Zip                      pgtype.Text        `json:"zip"`
	County                   pgtype.Text        `json:"county"`
	SiteStatus               pgtype.Text        `json:"site_status"`
	SiteType                 pgtype.Text        `json:"site_type"`
	SiteClass                pgtype.Text        `json:"site_class"`
	BuildStatus              pgtype.Text        `json:"build_status"`
	Landlord                 pgtype.Text        `json:"landlord"`
	LeaseAddress2            pgtype.Text        `json:"lease_address_2"`
	LeaseCity                pgtype.Text        `json:"lease_city"`
	LeaseState               pgtype.Text        `json:"lease_state"`
	LeaseZip                 pgtype.Text        `json:"lease_zip"`
	LeaseCounty              pgtype.Text        `json:"lease_county"`
	LeaseVendor              pgtype.Text        `json:"lease_vendor"`
	LeaseVendorRole          pgtype.Text        `json:"lease_vendor_role"`
	LeaseVendorAddress       pgtype.Text        `json:"lease_vendor_address"`
	LeaseVendorAddress2      pgtype.Text        `json:"lease_vendor_address2"`
	LeaseVendorCity          pgtype.Text        `json:"lease_vendor_city"`
	LeaseVendorState         pgtype.Text        `json:"lease_vendor_state"`
	LeaseVendorZip           pgtype.Text        `json:"lease_vendor_zip"`
	StructureVendor          pgtype.Text        `json:"structure_vendor"`
	StructureVendorRole      pgtype.Text        `json:"structure_vendor_role"`
	GroundVendor             pgtype.Text        `json:"ground_vendor"`
	GroundVendorRole         pgtype.Text        `json:"ground_vendor_role"`
	Latitude                 pgtype.Float8      `json:"latitude"`
	Longitude                pgtype.Float8      `json:"longitude"`
	Sap                      pgtype.Text        `json:"sap"`
	BusinessLicenseIds       pgtype.Text        `json:"business_license_ids"`
	LandlordReferenceID      pgtype.Text        `json:"landlord_reference_id"`
}

type Subcategory struct {
	ID          uuid.UUID        `json:"id"`
	CategoryID  uuid.UUID        `json:"category_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Embedding   []float32        `json:"embedding"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
