// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ProcessingState string

const (
	ProcessingStateProcessing ProcessingState = "processing"
	ProcessingStateComplete   ProcessingState = "complete"
	ProcessingStateFailed     ProcessingState = "failed"
)

func (e *ProcessingState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingState(s)
	case string:
		*e = ProcessingState(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingState: %T", src)
	}
	return nil
}

type NullProcessingState struct {
	ProcessingState ProcessingState `json:"processing_state"`
	Valid           bool            `json:"valid"` // Valid is true if ProcessingState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingState) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingState), nil
}

type RetryState string

const (
	RetryStatePending    RetryState = "pending"
	RetryStateRetried    RetryState = "retried"
	RetryStateDeadLetter RetryState = "dead_letter"
)

func (e *RetryState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RetryState(s)
	case string:
		*e = RetryState(s)
	default:
		return fmt.Errorf("unsupported scan type for RetryState: %T", src)
	}
	return nil
}

type NullRetryState struct {
	RetryState RetryState `json:"retry_state"`
	Valid      bool       `json:"valid"` // Valid is true if RetryState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRetryState) Scan(value interface{}) error {
	if value == nil {
		ns.RetryState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RetryState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRetryState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RetryState), nil
}

type AuditEvent struct {
	ID         uuid.UUID          `json:"id"`
	ResourceID uuid.UUID          `json:"resource_id"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	Actor      string             `json:"actor"`
	Metadata   json.RawMessage    `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Embedding   []float32        `json:"embedding"`
	Description string           `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Document struct {
	ID             uuid.UUID          `json:"id"`
	Filename       string             `json:"filename"`
	Filepath       string             `json:"filepath"`
	Classification string             `json:"classification"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DocumentStatus struct {
	DocumentID uuid.UUID          `json:"document_id"`
	StepName   string             `json:"step_name"`
	State      string             `json:"state"`
	Message    string             `json:"message"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type FailedMessage struct {
	ID              uuid.UUID          `json:"id"`
	DocumentID      uuid.UUID          `json:"document_id"`
	TopicName       string             `json:"topic_name"`
	ProtobufPayload []byte             `json:"protobuf_payload"`
	Headers         json.RawMessage    `json:"headers"`
	ErrorMessage    string             `json:"error_message"`
	RetryCount      *int32             `json:"retry_count"`
	RetryState      NullRetryState     `json:"retry_state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastRetryAt     pgtype.Timestamptz `json:"last_retry_at"`
}

type Metadata struct {
	ID                 int32              `json:"id"`
	SiteID             string             `json:"site_id"`
	DocumentType       string             `json:"document_type"`
	Confidence         *float64           `json:"confidence"`
	DocumentDate       pgtype.Date        `json:"document_date"`
	PortfolioType      string             `json:"portfolio_type"`
	DocumentAmount     *float64           `json:"document_amount"`
	LicensedEntity     string             `json:"licensed_entity"`
	LicensingAuthority string             `json:"licensing_authority"`
	DocumentFolder     string             `json:"document_folder"`
	Notes              string             `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ProcessingStep struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Site struct {
	ID                       int32              `json:"id"`
	Pk                       string             `json:"pk"`
	EmbeddingLandlord        *pgvector.Vector   `json:"embedding_landlord"`
	EmbeddingSiteAddress     *pgvector.Vector   `json:"embedding_site_address"`
	EmbeddingLandlordAddress *pgvector.Vector   `json:"embedding_landlord_address"`
	Timestamp                pgtype.Timestamptz `json:"timestamp"`
	SiteCode                 string             `json:"site_code"`
	PortfolioType            string             `json:"portfolio_type"`
	Channel                  string             `json:"channel"`
	UseType                  string             `json:"use_type"`
	Name                     string             `json:"name"`
	Status                   string             `json:"status"`
	SprintCascadeID          string             `json:"sprint_cascade_id"`
	Address                  string             `json:"address"`
	Address2                 string             `json:"address2"`
	City                     string             `json:"city"`
	State                    string             `json:"state"`
	Zip                      string             `json:"zip"`
	County                   string             `json:"county"`
	SiteStatus               string             `json:"site_status"`
	SiteType                 string             `json:"site_type"`
	SiteClass                string             `json:"site_class"`
	BuildStatus              string             `json:"build_status"`
	Landlord                 string             `json:"landlord"`
	LeaseAddress2            string             `json:"lease_address_2"`
	LeaseCity                string             `json:"lease_city"`
	LeaseState               string             `json:"lease_state"`
	LeaseZip                 string             `json:"lease_zip"`
	LeaseCounty              string             `json:"lease_county"`
	LeaseVendor              string             `json:"lease_vendor"`
	LeaseVendorRole          string             `json:"lease_vendor_role"`
	LeaseVendorAddress       string             `json:"lease_vendor_address"`
	LeaseVendorAddress2      string             `json:"lease_vendor_address2"`
	LeaseVendorCity          string             `json:"lease_vendor_city"`
	LeaseVendorState         string             `json:"lease_vendor_state"`
	LeaseVendorZip           string             `json:"lease_vendor_zip"`
	StructureVendor          string             `json:"structure_vendor"`
	StructureVendorRole      string             `json:"structure_vendor_role"`
	GroundVendor             string             `json:"ground_vendor"`
	GroundVendorRole         string             `json:"ground_vendor_role"`
	Latitude                 *float64           `json:"latitude"`
	Longitude                *float64           `json:"longitude"`
	Sap                      string             `json:"sap"`
	BusinessLicenseIds       string             `json:"business_license_ids"`
	LandlordReferenceID      string             `json:"landlord_reference_id"`
}

type Subcategory struct {
	ID          uuid.UUID        `json:"id"`
	CategoryID  uuid.UUID        `json:"category_id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Embedding   []float32        `json:"embedding"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
