// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAuditByResource(ctx context.Context, arg CountAuditByResourceParams) (int64, error)
	// =====================================
	// DASHBOARD / MONITORING
	// =====================================
	CountDocumentsByStepAndState(ctx context.Context) ([]CountDocumentsByStepAndStateRow, error)
	CountFailedMessagesByState(ctx context.Context) ([]CountFailedMessagesByStateRow, error)
	// =====================================================
	// AUDIT EVENTS QUERIES
	// =====================================================
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (CreateAuditEventRow, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// =====================================
	// DOCUMENTS
	// =====================================
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateMetadata(ctx context.Context, arg CreateMetadataParams) (int32, error)
	// =====================================
	// PROCESSING STEPS
	// =====================================
	CreateProcessingStep(ctx context.Context, arg CreateProcessingStepParams) error
	// =========================================
	// INSERT
	// =========================================
	CreateSite(ctx context.Context, arg CreateSiteParams) (int32, error)
	CreateSubcategory(ctx context.Context, arg CreateSubcategoryParams) (Subcategory, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteSubcategory(ctx context.Context, id uuid.UUID) error
	EnsureProcessingStep(ctx context.Context, name string) error
	GetAuditByAction(ctx context.Context, arg GetAuditByActionParams) ([]AuditEvent, error)
	GetAuditByActor(ctx context.Context, arg GetAuditByActorParams) ([]AuditEvent, error)
	GetAuditByMetadata(ctx context.Context, arg GetAuditByMetadataParams) ([]AuditEvent, error)
	GetAuditByResource(ctx context.Context, arg GetAuditByResourceParams) ([]AuditEvent, error)
	GetAuditByTimeRange(ctx context.Context, arg GetAuditByTimeRangeParams) ([]AuditEvent, error)
	GetAuditCursor(ctx context.Context, arg GetAuditCursorParams) ([]AuditEvent, error)
	GetAuditFiltered(ctx context.Context, arg GetAuditFilteredParams) ([]AuditEvent, error)
	GetAuditTimeline(ctx context.Context, arg GetAuditTimelineParams) ([]AuditEvent, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentStatuses(ctx context.Context, documentID uuid.UUID) ([]DocumentStatus, error)
	GetDocumentsByStepAndState(ctx context.Context, arg GetDocumentsByStepAndStateParams) ([]DocumentStatus, error)
	GetMetadataByDocumentType(ctx context.Context, documentType pgtype.Text) ([]Metadata, error)
	GetMetadataByID(ctx context.Context, id int32) (Metadata, error)
	GetMetadataByPortfolioType(ctx context.Context, portfolioType pgtype.Text) ([]Metadata, error)
	GetMetadataBySiteID(ctx context.Context, siteID pgtype.Text) ([]Metadata, error)
	GetPendingFailedMessages(ctx context.Context, limit int32) ([]FailedMessage, error)
	GetProcessingStep(ctx context.Context, name string) (ProcessingStep, error)
	// =========================================
	// READ QUERIES (ONLY REQUESTED FIELDS)
	// =========================================
	GetSiteByPK(ctx context.Context, pk pgtype.Text) (GetSiteByPKRow, error)
	GetSitesByAddress(ctx context.Context, address pgtype.Text) ([]GetSitesByAddressRow, error)
	GetSitesByLandlord(ctx context.Context, landlord pgtype.Text) ([]GetSitesByLandlordRow, error)
	GetSitesByPortfolioType(ctx context.Context, portfolioType pgtype.Text) ([]GetSitesByPortfolioTypeRow, error)
	GetSitesBySAP(ctx context.Context, sap pgtype.Text) ([]GetSitesBySAPRow, error)
	GetSitesBySiteCode(ctx context.Context, siteCode pgtype.Text) ([]GetSitesBySiteCodeRow, error)
	GetSitesByState(ctx context.Context, state pgtype.Text) ([]GetSitesByStateRow, error)
	GetSitesByZip(ctx context.Context, zip pgtype.Text) ([]GetSitesByZipRow, error)
	IncrementRetryCount(ctx context.Context, id uuid.UUID) error
	// =====================================
	// FAILED MESSAGE STORAGE
	// =====================================
	InsertFailedMessage(ctx context.Context, arg InsertFailedMessageParams) (FailedMessage, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListSubcategories(ctx context.Context) ([]ListSubcategoriesRow, error)
	ListSubcategoriesByCategory(ctx context.Context, categoryID uuid.UUID) ([]ListSubcategoriesByCategoryRow, error)
	MarkFailedMessageDeadLetter(ctx context.Context, id uuid.UUID) error
	MarkFailedMessageRetried(ctx context.Context, id uuid.UUID) error
	// =========================================
	// VECTOR SIMILARITY SEARCH
	// =========================================
	SimilarLandlord(ctx context.Context, arg SimilarLandlordParams) ([]SimilarLandlordRow, error)
	SimilarLandlordAddress(ctx context.Context, arg SimilarLandlordAddressParams) ([]SimilarLandlordAddressRow, error)
	SimilarSiteAddress(ctx context.Context, arg SimilarSiteAddressParams) ([]SimilarSiteAddressRow, error)
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error
	UpdateLandlordAddressEmbedding(ctx context.Context, arg UpdateLandlordAddressEmbeddingParams) error
	// =========================================
	// UPDATE EMBEDDINGS
	// =========================================
	UpdateLandlordEmbedding(ctx context.Context, arg UpdateLandlordEmbeddingParams) error
	UpdateMetadata(ctx context.Context, arg UpdateMetadataParams) error
	// =========================================
	// UPDATE ALL FIELDS
	// =========================================
	UpdateSite(ctx context.Context, arg UpdateSiteParams) error
	UpdateSiteAddressEmbedding(ctx context.Context, arg UpdateSiteAddressEmbeddingParams) error
	// =====================================
	// DOCUMENT STATUS
	// =====================================
	// Upsert current step status
	UpsertDocumentStatus(ctx context.Context, arg UpsertDocumentStatusParams) error
}

var _ Querier = (*Queries)(nil)
