// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditByResource = `-- name: CountAuditByResource :one
SELECT COUNT(*)
FROM audit_events
WHERE resource = $1
  AND resource_id = $2
`

type CountAuditByResourceParams struct {
	Resource   string      `json:"resource"`
	ResourceID pgtype.UUID `json:"resource_id"`
}

func (q *Queries) CountAuditByResource(ctx context.Context, arg CountAuditByResourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditByResource, arg.Resource, arg.ResourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByStepAndState = `-- name: CountDocumentsByStepAndState :many

SELECT
    step_name,
    state,
    COUNT(*) as total
FROM document_status
GROUP BY step_name, state
`

type CountDocumentsByStepAndStateRow struct {
	StepName string          `json:"step_name"`
	State    ProcessingState `json:"state"`
	Total    int64           `json:"total"`
}

// =====================================
// DASHBOARD / MONITORING
// =====================================
func (q *Queries) CountDocumentsByStepAndState(ctx context.Context) ([]CountDocumentsByStepAndStateRow, error) {
	rows, err := q.db.Query(ctx, countDocumentsByStepAndState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDocumentsByStepAndStateRow
	for rows.Next() {
		var i CountDocumentsByStepAndStateRow
		if err := rows.Scan(&i.StepName, &i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFailedMessagesByState = `-- name: CountFailedMessagesByState :many
SELECT
    retry_state,
    COUNT(*) as total
FROM failed_messages
GROUP BY retry_state
`

type CountFailedMessagesByStateRow struct {
	RetryState NullRetryState `json:"retry_state"`
	Total      int64          `json:"total"`
}

func (q *Queries) CountFailedMessagesByState(ctx context.Context) ([]CountFailedMessagesByStateRow, error) {
	rows, err := q.db.Query(ctx, countFailedMessagesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFailedMessagesByStateRow
	for rows.Next() {
		var i CountFailedMessagesByStateRow
		if err := rows.Scan(&i.RetryState, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAuditEvent = `-- name: CreateAuditEvent :one

INSERT INTO audit_events (
  resource,
  resource_id,
  action,
  actor,
  metadata
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateAuditEventParams struct {
	Resource   string      `json:"resource"`
	ResourceID pgtype.UUID `json:"resource_id"`
	Action     string      `json:"action"`
	Actor      pgtype.Text `json:"actor"`
	Metadata   []byte      `json:"metadata"`
}

type CreateAuditEventRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// =====================================================
// AUDIT EVENTS QUERIES
// =====================================================
func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (CreateAuditEventRow, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.Resource,
		arg.ResourceID,
		arg.Action,
		arg.Actor,
		arg.Metadata,
	)
	var i CreateAuditEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (
    id,
    filename,
    filepath,
    classification
)
VALUES ($1, $2, $3, $4)
RETURNING id, filename, filepath, classification, created_at, updated_at
`

type CreateDocumentParams struct {
	ID             pgtype.UUID `json:"id"`
	Filename       pgtype.Text `json:"filename"`
	Filepath       pgtype.Text `json:"filepath"`
	Classification pgtype.Text `json:"classification"`
}

// =====================================
// DOCUMENTS
// =====================================
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.Filename,
		arg.Filepath,
		arg.Classification,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Filepath,
		&i.Classification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProcessingStep = `-- name: CreateProcessingStep :exec

INSERT INTO processing_steps (
    name,
    description
)
VALUES ($1, $2)
ON CONFLICT (name) DO NOTHING
`

type CreateProcessingStepParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

// =====================================
// PROCESSING STEPS
// =====================================
func (q *Queries) CreateProcessingStep(ctx context.Context, arg CreateProcessingStepParams) error {
	_, err := q.db.Exec(ctx, createProcessingStep, arg.Name, arg.Description)
	return err
}

const ensureProcessingStep = `-- name: EnsureProcessingStep :exec
INSERT INTO processing_steps (name)
VALUES ($1)
ON CONFLICT (name) DO NOTHING
`

func (q *Queries) EnsureProcessingStep(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, ensureProcessingStep, name)
	return err
}

const getAuditByAction = `-- name: GetAuditByAction :many
SELECT id, resource_id, action, resource, actor, metadata, created_at
FROM audit_events
WHERE action = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetAuditByAction(ctx context.Context, arg GetAuditByActionParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Action,
			&i.Resource,
			&i.Actor,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditByActor = `-- name: GetAuditByActor :many
SELECT id, resource_id, action, resource, actor, metadata, created_at
FROM audit_events
WHERE actor = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditByActorParams struct {
	Actor  pgtype.Text `json:"actor"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetAuditByActor(ctx context.Context, arg GetAuditByActorParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditByActor, arg.Actor, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Action,
			&i.Resource,
			&i.Actor,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditByMetadata = `-- name: GetAuditByMetadata :many
SELECT id, resource_id, action, resource, actor, metadata, created_at
FROM audit_events
WHERE metadata @> $1::jsonb
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditByMetadataParams struct {
	Column1 []byte `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetAuditByMetadata(ctx context.Context, arg GetAuditByMetadataParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditByMetadata, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Action,
			&i.Resource,
			&i.Actor,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditByResource = `-- name: GetAuditByResource :many
SELECT id, resource_id, action, resource, actor, metadata, created_at
FROM audit_events
WHERE resource = $1
  AND resource_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetAuditByResourceParams struct {
	Resource   string      `json:"resource"`
	ResourceID pgtype.UUID `json:"resource_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) GetAuditByResource(ctx context.Context, arg GetAuditByResourceParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditByResource,
		arg.Resource,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Action,
			&i.Resource,
			&i.Actor,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditByTimeRange = `-- name: GetAuditByTimeRange :many
SELECT id, resource_id, action, resource, actor, metadata, created_at
FROM audit_events
WHERE created_at BETWEEN $1 AND $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetAuditByTimeRangeParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) GetAuditByTimeRange(ctx context.Context, arg GetAuditByTimeRangeParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditByTimeRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Action,
			&i.Resource,
			&i.Actor,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditCursor = `-- name: GetAuditCursor :many
SELECT id, resource_id, action, resource, actor, metadata, created_at
FROM audit_events
WHERE resource = $1
  AND resource_id = $2
  AND created_at < $3
ORDER BY created_at DESC
LIMIT $4
`

type GetAuditCursorParams struct {
	Resource   string             `json:"resource"`
	ResourceID pgtype.UUID        `json:"resource_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) GetAuditCursor(ctx context.Context, arg GetAuditCursorParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditCursor,
		arg.Resource,
		arg.ResourceID,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Action,
			&i.Resource,
			&i.Actor,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditFiltered = `-- name: GetAuditFiltered :many
SELECT id, resource_id, action, resource, actor, metadata, created_at
FROM audit_events
WHERE ($1::text IS NULL OR resource = $1)
  AND ($2::uuid IS NULL OR resource_id = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::text IS NULL OR actor = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT $7 OFFSET $8
`

type GetAuditFilteredParams struct {
	Column1 string             `json:"column_1"`
	Column2 pgtype.UUID        `json:"column_2"`
	Column3 string             `json:"column_3"`
	Column4 string             `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Column6 pgtype.Timestamptz `json:"column_6"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) GetAuditFiltered(ctx context.Context, arg GetAuditFilteredParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Action,
			&i.Resource,
			&i.Actor,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditTimeline = `-- name: GetAuditTimeline :many
SELECT id, resource_id, action, resource, actor, metadata, created_at
FROM audit_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAuditTimelineParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAuditTimeline(ctx context.Context, arg GetAuditTimelineParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditTimeline, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Action,
			&i.Resource,
			&i.Actor,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, filename, filepath, classification, created_at, updated_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Filepath,
		&i.Classification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentStatuses = `-- name: GetDocumentStatuses :many
SELECT document_id, step_name, state, message, updated_at
FROM document_status
WHERE document_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetDocumentStatuses(ctx context.Context, documentID pgtype.UUID) ([]DocumentStatus, error) {
	rows, err := q.db.Query(ctx, getDocumentStatuses, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentStatus
	for rows.Next() {
		var i DocumentStatus
		if err := rows.Scan(
			&i.DocumentID,
			&i.StepName,
			&i.State,
			&i.Message,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByStepAndState = `-- name: GetDocumentsByStepAndState :many
SELECT document_id, step_name, state, message, updated_at
FROM document_status
WHERE step_name = $1
AND state = $2
ORDER BY updated_at DESC
LIMIT $3 OFFSET $4
`

type GetDocumentsByStepAndStateParams struct {
	StepName string          `json:"step_name"`
	State    ProcessingState `json:"state"`
	Limit    int32           `json:"limit"`
	Offset   int32           `json:"offset"`
}

func (q *Queries) GetDocumentsByStepAndState(ctx context.Context, arg GetDocumentsByStepAndStateParams) ([]DocumentStatus, error) {
	rows, err := q.db.Query(ctx, getDocumentsByStepAndState,
		arg.StepName,
		arg.State,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentStatus
	for rows.Next() {
		var i DocumentStatus
		if err := rows.Scan(
			&i.DocumentID,
			&i.StepName,
			&i.State,
			&i.Message,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingFailedMessages = `-- name: GetPendingFailedMessages :many
SELECT id, document_id, topic_name, protobuf_payload, headers, error_message, retry_count, retry_state, created_at, last_retry_at
FROM failed_messages
WHERE retry_state = 'pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) GetPendingFailedMessages(ctx context.Context, limit int32) ([]FailedMessage, error) {
	rows, err := q.db.Query(ctx, getPendingFailedMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailedMessage
	for rows.Next() {
		var i FailedMessage
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TopicName,
			&i.ProtobufPayload,
			&i.Headers,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.RetryState,
			&i.CreatedAt,
			&i.LastRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessingStep = `-- name: GetProcessingStep :one
SELECT name, description, created_at
FROM processing_steps
WHERE name = $1
`

func (q *Queries) GetProcessingStep(ctx context.Context, name string) (ProcessingStep, error) {
	row := q.db.QueryRow(ctx, getProcessingStep, name)
	var i ProcessingStep
	err := row.Scan(&i.Name, &i.Description, &i.CreatedAt)
	return i, err
}

const incrementRetryCount = `-- name: IncrementRetryCount :exec
UPDATE failed_messages
SET
    retry_count = retry_count + 1,
    last_retry_at = now()
WHERE id = $1
`

func (q *Queries) IncrementRetryCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementRetryCount, id)
	return err
}

const insertFailedMessage = `-- name: InsertFailedMessage :one

INSERT INTO failed_messages (
    document_id,
    topic_name,
    protobuf_payload,
    headers,
    error_message
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_id, topic_name, protobuf_payload, headers, error_message, retry_count, retry_state, created_at, last_retry_at
`

type InsertFailedMessageParams struct {
	DocumentID      pgtype.UUID `json:"document_id"`
	TopicName       string      `json:"topic_name"`
	ProtobufPayload []byte      `json:"protobuf_payload"`
	Headers         []byte      `json:"headers"`
	ErrorMessage    pgtype.Text `json:"error_message"`
}

// =====================================
// FAILED MESSAGE STORAGE
// =====================================
func (q *Queries) InsertFailedMessage(ctx context.Context, arg InsertFailedMessageParams) (FailedMessage, error) {
	row := q.db.QueryRow(ctx, insertFailedMessage,
		arg.DocumentID,
		arg.TopicName,
		arg.ProtobufPayload,
		arg.Headers,
		arg.ErrorMessage,
	)
	var i FailedMessage
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.TopicName,
		&i.ProtobufPayload,
		&i.Headers,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.RetryState,
		&i.CreatedAt,
		&i.LastRetryAt,
	)
	return i, err
}

const markFailedMessageDeadLetter = `-- name: MarkFailedMessageDeadLetter :exec
UPDATE failed_messages
SET
    retry_state = 'dead_letter',
    last_retry_at = now()
WHERE id = $1
`

func (q *Queries) MarkFailedMessageDeadLetter(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFailedMessageDeadLetter, id)
	return err
}

const markFailedMessageRetried = `-- name: MarkFailedMessageRetried :exec
UPDATE failed_messages
SET
    retry_state = 'retried',
    retry_count = retry_count + 1,
    last_retry_at = now()
WHERE id = $1
`

func (q *Queries) MarkFailedMessageRetried(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFailedMessageRetried, id)
	return err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE document_status
SET
    state = $3,
    message = $4,
    updated_at = now()
WHERE document_id = $1
AND step_name = $2
`

type UpdateDocumentStatusParams struct {
	DocumentID pgtype.UUID     `json:"document_id"`
	StepName   string          `json:"step_name"`
	State      ProcessingState `json:"state"`
	Message    pgtype.Text     `json:"message"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus,
		arg.DocumentID,
		arg.StepName,
		arg.State,
		arg.Message,
	)
	return err
}

const upsertDocumentStatus = `-- name: UpsertDocumentStatus :exec

INSERT INTO document_status (
    document_id,
    step_name,
    state,
    message
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (document_id, step_name)
DO UPDATE SET
    state = EXCLUDED.state,
    message = EXCLUDED.message,
    updated_at = now()
`

type UpsertDocumentStatusParams struct {
	DocumentID pgtype.UUID     `json:"document_id"`
	StepName   string          `json:"step_name"`
	State      ProcessingState `json:"state"`
	Message    pgtype.Text     `json:"message"`
}

// =====================================
// DOCUMENT STATUS
// =====================================
// Upsert current step status
func (q *Queries) UpsertDocumentStatus(ctx context.Context, arg UpsertDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, upsertDocumentStatus,
		arg.DocumentID,
		arg.StepName,
		arg.State,
		arg.Message,
	)
	return err
}
