// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: users/v1/user.proto

package usersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Groups        []string               `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	Permissions   []*Permissions         `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_users_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *User) GetPermissions() []*Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UsersEmails   []string               `protobuf:"bytes,2,rep,name=users_emails,json=usersEmails,proto3" json:"users_emails,omitempty"`
	Permissions   []*Permissions         `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_users_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetUsersEmails() []string {
	if x != nil {
		return x.UsersEmails
	}
	return nil
}

func (x *Group) GetPermissions() []*Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Permissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_users_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *Permissions) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permissions) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_users_v1_user_proto protoreflect.FileDescriptor

const file_users_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x13users/v1/user.proto\x12\busers.v1\"m\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06groups\x18\x04 \x03(\tR\x06groups\x127\n" +
	"\vpermissions\x18\x05 \x03(\v2\x15.users.v1.PermissionsR\vpermissions\"w\n" +
	"\x05Group\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fusers_emails\x18\x02 \x03(\tR\vusersEmails\x127\n" +
	"\vpermissions\x18\x05 \x03(\v2\x15.users.v1.PermissionsR\vpermissions\"A\n" +
	"\vPermissions\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06actionB5Z3github.com/bexprt/bexgen-client/pb/users/v1;usersv1b\x06proto3"

var (
	file_users_v1_user_proto_rawDescOnce sync.Once
	file_users_v1_user_proto_rawDescData []byte
)

func file_users_v1_user_proto_rawDescGZIP() []byte {
	file_users_v1_user_proto_rawDescOnce.Do(func() {
		file_users_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_user_proto_rawDesc), len(file_users_v1_user_proto_rawDesc)))
	})
	return file_users_v1_user_proto_rawDescData
}

var file_users_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_users_v1_user_proto_goTypes = []any{
	(*User)(nil),        // 0: users.v1.User
	(*Group)(nil),       // 1: users.v1.Group
	(*Permissions)(nil), // 2: users.v1.Permissions
}
var file_users_v1_user_proto_depIdxs = []int32{
	2, // 0: users.v1.User.permissions:type_name -> users.v1.Permissions
	2, // 1: users.v1.Group.permissions:type_name -> users.v1.Permissions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_users_v1_user_proto_init() }
func file_users_v1_user_proto_init() {
	if File_users_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_user_proto_rawDesc), len(file_users_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_v1_user_proto_goTypes,
		DependencyIndexes: file_users_v1_user_proto_depIdxs,
		MessageInfos:      file_users_v1_user_proto_msgTypes,
	}.Build()
	File_users_v1_user_proto = out.File
	file_users_v1_user_proto_goTypes = nil
	file_users_v1_user_proto_depIdxs = nil
}
